/*
 * Square Connect API
 *
 * Client library for accessing the Square Connect APIs
 *
 * API version: 2.0
 * Contact: developers@squareup.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package models

// Represents a refund processed for a Square transaction.
type Refund struct {
	// The refund's unique ID.
	Id string `json:"id"`
	// The ID of the refund's associated location.
	LocationId string `json:"location_id"`
	// The ID of the transaction that the refunded tender is part of.
	TransactionId string `json:"transaction_id,omitempty"`
	// The ID of the refunded tender.
	TenderId string `json:"tender_id"`
	// The timestamp for when the refund was created, in RFC 3339 format.
	CreatedAt string `json:"created_at,omitempty"`
	// The reason for the refund being issued.
	Reason string `json:"reason"`
	// The amount of money refunded to the buyer.
	AmountMoney *Money `json:"amount_money"`
	// The current status of the refund (`PENDING`, `APPROVED`, `REJECTED`, or `FAILED`).
	Status string `json:"status"`
	// The amount of Square processing fee money refunded to the *merchant*.
	ProcessingFeeMoney *Money `json:"processing_fee_money,omitempty"`
	// Additional recipients (other than the merchant) receiving a portion of this refund. For example, fees assessed on a refund of a purchase by a third party integration.
	AdditionalRecipients []AdditionalRecipient `json:"additional_recipients,omitempty"`
}
