/*
 * Square Connect API
 *
 * Client library for accessing the Square Connect APIs
 *
 * API version: 2.0
 * Contact: developers@squareup.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package models

// A filter to select customers based on exact or fuzzy matching of customer attributes against a specified query. Depending on the customer attributes,  the filter can be case-sensitive. This filter can be exact or fuzzy, but it cannot be both.
type CustomerTextFilter struct {
	// Use the exact filter to select customers whose attributes match exactly the specified query.
	Exact string `json:"exact,omitempty"`
	// Use the fuzzy filter to select customers whose attributes match the specified query  in a fuzzy manner. When the fuzzy option is used, search queries are tokenized, and then  each query token must be matched somewhere in the searched attribute. For single token queries,  this is effectively the same behavior as a partial match operation.
	Fuzzy string `json:"fuzzy,omitempty"`
}
