/*
 * Square Connect API
 *
 * Client library for accessing the Square Connect APIs
 *
 * API version: 2.0
 * Contact: developers@squareup.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package models
// CardType : Indicates a card's type, such as `CREDIT` or `DEBIT`.
type CardType string

// List of CardType
const (
	UNKNOWN_CARD_TYPE_CardType CardType = "UNKNOWN_CARD_TYPE"
	CREDIT_CardType CardType = "CREDIT"
	DEBIT_CardType CardType = "DEBIT"
)
