/*
 * Square Connect API
 *
 * Client library for accessing the Square Connect APIs
 *
 * API version: 2.0
 * Contact: developers@squareup.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package models

// Represents the details of a tender with `type` `BUY_NOW_PAY_LATER`.
type TenderBuyNowPayLaterDetails struct {
	// The Buy Now Pay Later brand.
	BuyNowPayLaterBrand string `json:"buy_now_pay_later_brand,omitempty"`
	// The buy now pay later payment's current state (such as `AUTHORIZED` or `CAPTURED`). See [TenderBuyNowPayLaterDetailsStatus](https://developer.squareup.com/reference/square_2023-12-13/enums/TenderBuyNowPayLaterDetailsStatus) for possible values.
	Status string `json:"status,omitempty"`
}
