/*
 * Square Connect API
 *
 * Client library for accessing the Square Connect APIs
 *
 * API version: 2.0
 * Contact: developers@squareup.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package models

// A filter based on order `source` information.
type SearchOrdersSourceFilter struct {
	// Filters by the [Source](https://developer.squareup.com/reference/square_2023-12-13/objects/OrderSource) `name`. The filter returns any orders with a `source.name` that matches any of the listed source names.  Max: 10 source names.
	SourceNames []string `json:"source_names,omitempty"`
}
