/*
 * Square Connect API
 *
 * Client library for accessing the Square Connect APIs
 *
 * API version: 2.0
 * Contact: developers@squareup.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package models

// Defines the response returned by[CompletePayment](https://developer.squareup.com/reference/square_2023-12-13/payments-api/complete-payment).
type CompletePaymentResponse struct {
	// Information about errors encountered during the request.
	Errors []ModelError `json:"errors,omitempty"`
	// The successfully completed payment.
	Payment *Payment `json:"payment,omitempty"`
}
