/*
 * Square Connect API
 *
 * Client library for accessing the Square Connect APIs
 *
 * API version: 2.0
 * Contact: developers@squareup.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package models

// Represents one delete within the bulk operation.
type BulkDeleteOrderCustomAttributesRequestDeleteCustomAttribute struct {
	// The key of the custom attribute to delete.  This key must match the key  of an existing custom attribute definition.
	Key string `json:"key,omitempty"`
	// The ID of the target [order](https://developer.squareup.com/reference/square_2023-12-13/objects/Order).
	OrderId string `json:"order_id"`
}
