/*
 * Square Connect API
 *
 * Client library for accessing the Square Connect APIs
 *
 * API version: 2.0
 * Contact: developers@squareup.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package models
// TenderBuyNowPayLaterDetailsBrand : 
type TenderBuyNowPayLaterDetailsBrand string

// List of TenderBuyNowPayLaterDetailsBrand
const (
	OTHER_BRAND_TenderBuyNowPayLaterDetailsBrand TenderBuyNowPayLaterDetailsBrand = "OTHER_BRAND"
	AFTERPAY_TenderBuyNowPayLaterDetailsBrand TenderBuyNowPayLaterDetailsBrand = "AFTERPAY"
)
