/*
 * Square Connect API
 *
 * Client library for accessing the Square Connect APIs
 *
 * API version: 2.0
 * Contact: developers@squareup.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package models
// TenderSquareAccountDetailsStatus : 
type TenderSquareAccountDetailsStatus string

// List of TenderSquareAccountDetailsStatus
const (
	AUTHORIZED_TenderSquareAccountDetailsStatus TenderSquareAccountDetailsStatus = "AUTHORIZED"
	CAPTURED_TenderSquareAccountDetailsStatus TenderSquareAccountDetailsStatus = "CAPTURED"
	VOIDED_TenderSquareAccountDetailsStatus TenderSquareAccountDetailsStatus = "VOIDED"
	FAILED_TenderSquareAccountDetailsStatus TenderSquareAccountDetailsStatus = "FAILED"
)
