/*
 * Square Connect API
 *
 * Client library for accessing the Square Connect APIs
 *
 * API version: 2.0
 * Contact: developers@squareup.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package models

// Contains the measurement unit for a quantity and a precision that specifies the number of digits after the decimal point for decimal quantities.
type OrderQuantityUnit struct {
	// A [MeasurementUnit](https://developer.squareup.com/reference/square_2023-12-13/objects/MeasurementUnit) that represents the unit of measure for the quantity.
	MeasurementUnit *MeasurementUnit `json:"measurement_unit,omitempty"`
	// For non-integer quantities, represents the number of digits after the decimal point that are recorded for this quantity.  For example, a precision of 1 allows quantities such as `\"1.0\"` and `\"1.1\"`, but not `\"1.01\"`.  Min: 0. Max: 5.
	Precision int32 `json:"precision,omitempty"`
	// The catalog object ID referencing the [CatalogMeasurementUnit](https://developer.squareup.com/reference/square_2023-12-13/objects/CatalogMeasurementUnit).  This field is set when this is a catalog-backed measurement unit.
	CatalogObjectId string `json:"catalog_object_id,omitempty"`
	// The version of the catalog object that this measurement unit references.  This field is set when this is a catalog-backed measurement unit.
	CatalogVersion int64 `json:"catalog_version,omitempty"`
}
