/*
 * Square Connect API
 *
 * Client library for accessing the Square Connect APIs
 *
 * API version: 2.0
 * Contact: developers@squareup.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package models

// 
type OrderUpdatedObject struct {
	// Information about the updated order.
	OrderUpdated *OrderUpdated `json:"order_updated,omitempty"`
}
