/*
 * Square Connect API
 *
 * Client library for accessing the Square Connect APIs
 *
 * API version: 2.0
 * Contact: developers@squareup.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package models
// MeasurementUnitArea : Unit of area used to measure a quantity.
type MeasurementUnitArea string

// List of MeasurementUnitArea
const (
	IMPERIAL_ACRE_MeasurementUnitArea MeasurementUnitArea = "IMPERIAL_ACRE"
	IMPERIAL_SQUARE_INCH_MeasurementUnitArea MeasurementUnitArea = "IMPERIAL_SQUARE_INCH"
	IMPERIAL_SQUARE_FOOT_MeasurementUnitArea MeasurementUnitArea = "IMPERIAL_SQUARE_FOOT"
	IMPERIAL_SQUARE_YARD_MeasurementUnitArea MeasurementUnitArea = "IMPERIAL_SQUARE_YARD"
	IMPERIAL_SQUARE_MILE_MeasurementUnitArea MeasurementUnitArea = "IMPERIAL_SQUARE_MILE"
	METRIC_SQUARE_CENTIMETER_MeasurementUnitArea MeasurementUnitArea = "METRIC_SQUARE_CENTIMETER"
	METRIC_SQUARE_METER_MeasurementUnitArea MeasurementUnitArea = "METRIC_SQUARE_METER"
	METRIC_SQUARE_KILOMETER_MeasurementUnitArea MeasurementUnitArea = "METRIC_SQUARE_KILOMETER"
)
