/*
 * Square Connect API
 *
 * Client library for accessing the Square Connect APIs
 *
 * API version: 2.0
 * Contact: developers@squareup.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package models

// Defines the body parameters that can be included in a request to the [UpdateCustomerGroup](https://developer.squareup.com/reference/square_2023-12-13/customer-groups-api/update-customer-group) endpoint.
type UpdateCustomerGroupRequest struct {
	// The `CustomerGroup` object including all the updates you want to make.
	Group *CustomerGroup `json:"group"`
}
