/*
 * Square Connect API
 *
 * Client library for accessing the Square Connect APIs
 *
 * API version: 2.0
 * Contact: developers@squareup.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package models

// Defines the fields that are included in the response body of a request to the [PayOrder](https://developer.squareup.com/reference/square_2023-12-13/orders-api/pay-order) endpoint.
type PayOrderResponse struct {
	// Any errors that occurred during the request.
	Errors []ModelError `json:"errors,omitempty"`
	// The paid, updated [order](https://developer.squareup.com/reference/square_2023-12-13/objects/Order).
	Order *Order `json:"order,omitempty"`
}
