/*
 * Square Connect API
 *
 * Client library for accessing the Square Connect APIs
 *
 * API version: 2.0
 * Contact: developers@squareup.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package models
// FulfillmentPickupDetailsScheduleType : The schedule type of the pickup fulfillment.
type FulfillmentPickupDetailsScheduleType string

// List of FulfillmentPickupDetailsScheduleType
const (
	SCHEDULED_FulfillmentPickupDetailsScheduleType FulfillmentPickupDetailsScheduleType = "SCHEDULED"
	ASAP_FulfillmentPickupDetailsScheduleType FulfillmentPickupDetailsScheduleType = "ASAP"
)
