/*
 * Square Connect API
 *
 * Client library for accessing the Square Connect APIs
 *
 * API version: 2.0
 * Contact: developers@squareup.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package models

// Represents a unit of measurement to use with a quantity, such as ounces or inches. Exactly one of the following fields are required: `custom_unit`, `area_unit`, `length_unit`, `volume_unit`, and `weight_unit`.
type MeasurementUnit struct {
	// A custom unit of measurement defined by the seller using the Point of Sale app or ad-hoc as an order line item.
	CustomUnit *MeasurementUnitCustom `json:"custom_unit,omitempty"`
	// Represents a standard area unit.
	AreaUnit string `json:"area_unit,omitempty"`
	// Represents a standard length unit.
	LengthUnit string `json:"length_unit,omitempty"`
	// Represents a standard volume unit.
	VolumeUnit string `json:"volume_unit,omitempty"`
	// Represents a standard unit of weight or mass.
	WeightUnit string `json:"weight_unit,omitempty"`
	// Reserved for API integrations that lack the ability to specify a real measurement unit
	GenericUnit string `json:"generic_unit,omitempty"`
	// Represents a standard unit of time.
	TimeUnit string `json:"time_unit,omitempty"`
	// Represents the type of the measurement unit.
	Type_ string `json:"type,omitempty"`
}
