/*
 * Square Connect API
 *
 * Client library for accessing the Square Connect APIs
 *
 * API version: 2.0
 * Contact: developers@squareup.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package models
// OrderFulfillmentPickupDetailsScheduleType : The schedule type of the pickup fulfillment.
type OrderFulfillmentPickupDetailsScheduleType string

// List of OrderFulfillmentPickupDetailsScheduleType
const (
	SCHEDULED_OrderFulfillmentPickupDetailsScheduleType OrderFulfillmentPickupDetailsScheduleType = "SCHEDULED"
	ASAP_OrderFulfillmentPickupDetailsScheduleType OrderFulfillmentPickupDetailsScheduleType = "ASAP"
)
