/*
 * Square Connect API
 *
 * Client library for accessing the Square Connect APIs
 *
 * API version: 2.0
 * Contact: developers@squareup.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package models

// The custom attribute filters in a set of [customer filters](https://developer.squareup.com/reference/square_2023-12-13/objects/CustomerFilter) used in a search query. Use this filter to search based on [custom attributes](https://developer.squareup.com/reference/square_2023-12-13/objects/CustomAttribute) that are assigned to customer profiles. For more information, see [Search by custom attribute](https://developer.squareup.com/docs/customers-api/use-the-api/search-customers#search-by-custom-attribute).
type CustomerCustomAttributeFilters struct {
	// The custom attribute filters. Each filter must specify `key` and include the `filter` field with a type-specific filter, the `updated_at` field, or both. The provided keys must be unique within the list of custom attribute filters.
	Filters []CustomerCustomAttributeFilter `json:"filters,omitempty"`
}
