/*
 * Square Connect API
 *
 * Client library for accessing the Square Connect APIs
 *
 * API version: 2.0
 * Contact: developers@squareup.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package models

// Represents a response from a bulk upsert of order custom attributes.
type BulkUpsertOrderCustomAttributesResponse struct {
	// Any errors that occurred during the request.
	Errors []ModelError `json:"errors,omitempty"`
	//  A map of responses that correspond to individual upsert operations for custom attributes.
	Values map[string]UpsertOrderCustomAttributeResponse `json:"values"`
}
