/*
 * Square Connect API
 *
 * Client library for accessing the Square Connect APIs
 *
 * API version: 2.0
 * Contact: developers@squareup.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package models
// MeasurementUnitTime : Unit of time used to measure a quantity (a duration).
type MeasurementUnitTime string

// List of MeasurementUnitTime
const (
	MILLISECOND_MeasurementUnitTime MeasurementUnitTime = "GENERIC_MILLISECOND"
	SECOND_MeasurementUnitTime MeasurementUnitTime = "GENERIC_SECOND"
	MINUTE_MeasurementUnitTime MeasurementUnitTime = "GENERIC_MINUTE"
	HOUR_MeasurementUnitTime MeasurementUnitTime = "GENERIC_HOUR"
	DAY_MeasurementUnitTime MeasurementUnitTime = "GENERIC_DAY"
)
