/*
 * Square Connect API
 *
 * Client library for accessing the Square Connect APIs
 *
 * API version: 2.0
 * Contact: developers@squareup.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package models

// The set of line items, service charges, taxes, discounts, tips, and other items being returned in an order.
type OrderReturn struct {
	// A unique ID that identifies the return only within this order.
	Uid string `json:"uid,omitempty"`
	// An order that contains the original sale of these return line items. This is unset for unlinked returns.
	SourceOrderId string `json:"source_order_id,omitempty"`
	// A collection of line items that are being returned.
	ReturnLineItems []OrderReturnLineItem `json:"return_line_items,omitempty"`
	// A collection of service charges that are being returned.
	ReturnServiceCharges []OrderReturnServiceCharge `json:"return_service_charges,omitempty"`
	// A collection of references to taxes being returned for an order, including the total applied tax amount to be returned. The taxes must reference a top-level tax ID from the source order.
	ReturnTaxes []OrderReturnTax `json:"return_taxes,omitempty"`
	// A collection of references to discounts being returned for an order, including the total applied discount amount to be returned. The discounts must reference a top-level discount ID from the source order.
	ReturnDiscounts []OrderReturnDiscount `json:"return_discounts,omitempty"`
	// A positive or negative rounding adjustment to the total value being returned. Adjustments are commonly used to apply cash rounding when the minimum unit of the account is smaller than the lowest physical denomination of the currency.
	RoundingAdjustment *OrderRoundingAdjustment `json:"rounding_adjustment,omitempty"`
	// An aggregate monetary value being returned by this return entry.
	ReturnAmounts *OrderMoneyAmounts `json:"return_amounts,omitempty"`
}
