/*
 * Square Connect API
 *
 * Client library for accessing the Square Connect APIs
 *
 * API version: 2.0
 * Contact: developers@squareup.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package models
// FulfillmentDeliveryDetailsOrderFulfillmentDeliveryDetailsScheduleType : The schedule type of the delivery fulfillment.
type FulfillmentDeliveryDetailsOrderFulfillmentDeliveryDetailsScheduleType string

// List of FulfillmentDeliveryDetailsOrderFulfillmentDeliveryDetailsScheduleType
const (
	SCHEDULED_FulfillmentDeliveryDetailsOrderFulfillmentDeliveryDetailsScheduleType FulfillmentDeliveryDetailsOrderFulfillmentDeliveryDetailsScheduleType = "SCHEDULED"
	ASAP_FulfillmentDeliveryDetailsOrderFulfillmentDeliveryDetailsScheduleType FulfillmentDeliveryDetailsOrderFulfillmentDeliveryDetailsScheduleType = "ASAP"
)
