/*
 * Square Connect API
 *
 * Client library for accessing the Square Connect APIs
 *
 * API version: 2.0
 * Contact: developers@squareup.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package models

// Details about the device that took the payment.
type DeviceDetails struct {
	// The Square-issued ID of the device.
	DeviceId string `json:"device_id,omitempty"`
	// The Square-issued installation ID for the device.
	DeviceInstallationId string `json:"device_installation_id,omitempty"`
	// The name of the device set by the seller.
	DeviceName string `json:"device_name,omitempty"`
}
