/*
 * Square Connect API
 *
 * Client library for accessing the Square Connect APIs
 *
 * API version: 2.0
 * Contact: developers@squareup.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package models
// OrderLineItemItemType : Represents the line item type.
type OrderLineItemItemType string

// List of OrderLineItemItemType
const (
	ITEM_OrderLineItemItemType OrderLineItemItemType = "ITEM"
	CUSTOM_AMOUNT_OrderLineItemItemType OrderLineItemItemType = "CUSTOM_AMOUNT"
	GIFT_CARD_OrderLineItemItemType OrderLineItemItemType = "GIFT_CARD"
)
