/*
 * Square Connect API
 *
 * Client library for accessing the Square Connect APIs
 *
 * API version: 2.0
 * Contact: developers@squareup.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package models

// Represents additional details of a tender with `type` `CARD` or `SQUARE_GIFT_CARD`
type TenderCardDetails struct {
	// The credit card payment's current state (such as `AUTHORIZED` or `CAPTURED`). See [TenderCardDetailsStatus](https://developer.squareup.com/reference/square_2023-12-13/enums/TenderCardDetailsStatus) for possible values.
	Status string `json:"status,omitempty"`
	// The credit card's non-confidential details.
	Card *Card `json:"card,omitempty"`
	// The method used to enter the card's details for the transaction.
	EntryMethod string `json:"entry_method,omitempty"`
}
