/*
 * Square Connect API
 *
 * Client library for accessing the Square Connect APIs
 *
 * API version: 2.0
 * Contact: developers@squareup.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package models
// OrderLineItemDiscountScope : Indicates whether this is a line-item or order-level discount.
type OrderLineItemDiscountScope string

// List of OrderLineItemDiscountScope
const (
	OTHER_DISCOUNT_SCOPE_OrderLineItemDiscountScope OrderLineItemDiscountScope = "OTHER_DISCOUNT_SCOPE"
	LINE_ITEM_OrderLineItemDiscountScope OrderLineItemDiscountScope = "LINE_ITEM"
	ORDER_OrderLineItemDiscountScope OrderLineItemDiscountScope = "ORDER"
)
