/*
 * Square Connect API
 *
 * Client library for accessing the Square Connect APIs
 *
 * API version: 2.0
 * Contact: developers@squareup.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package models
// TenderBuyNowPayLaterDetailsStatus : 
type TenderBuyNowPayLaterDetailsStatus string

// List of TenderBuyNowPayLaterDetailsStatus
const (
	AUTHORIZED_TenderBuyNowPayLaterDetailsStatus TenderBuyNowPayLaterDetailsStatus = "AUTHORIZED"
	CAPTURED_TenderBuyNowPayLaterDetailsStatus TenderBuyNowPayLaterDetailsStatus = "CAPTURED"
	VOIDED_TenderBuyNowPayLaterDetailsStatus TenderBuyNowPayLaterDetailsStatus = "VOIDED"
	FAILED_TenderBuyNowPayLaterDetailsStatus TenderBuyNowPayLaterDetailsStatus = "FAILED"
)
