/*
 * Square Connect API
 *
 * Client library for accessing the Square Connect APIs
 *
 * API version: 2.0
 * Contact: developers@squareup.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package models
// TenderCardDetailsStatus : Indicates the card transaction's current status.
type TenderCardDetailsStatus string

// List of TenderCardDetailsStatus
const (
	AUTHORIZED_TenderCardDetailsStatus TenderCardDetailsStatus = "AUTHORIZED"
	CAPTURED_TenderCardDetailsStatus TenderCardDetailsStatus = "CAPTURED"
	VOIDED_TenderCardDetailsStatus TenderCardDetailsStatus = "VOIDED"
	FAILED_TenderCardDetailsStatus TenderCardDetailsStatus = "FAILED"
)
