/*
 * Square Connect API
 *
 * Client library for accessing the Square Connect APIs
 *
 * API version: 2.0
 * Contact: developers@squareup.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package models

// Describes a request to retrieve a payment using  [GetPayment](https://developer.squareup.com/reference/square_2023-12-13/payments-api/get-payment).
type GetPaymentRequest struct {
}
