/*
 * Square Connect API
 *
 * Client library for accessing the Square Connect APIs
 *
 * API version: 2.0
 * Contact: developers@squareup.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package models

// 
type OrderLineItemAppliedServiceCharge struct {
	// A unique ID that identifies the applied service charge only within this order.
	Uid string `json:"uid,omitempty"`
	// The `uid` of the service charge that the applied service charge represents. It must reference a service charge present in the `order.service_charges` field.  This field is immutable. To change which service charges apply to a line item, delete and add a new `OrderLineItemAppliedServiceCharge`.
	ServiceChargeUid string `json:"service_charge_uid"`
	// The amount of money applied by the service charge to the line item.
	AppliedMoney *Money `json:"applied_money,omitempty"`
}
