/*
 * Square Connect API
 *
 * Client library for accessing the Square Connect APIs
 *
 * API version: 2.0
 * Contact: developers@squareup.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package models

// Either the `order_entries` or `orders` field is set, depending on whether `return_entries` is set on the [SearchOrdersRequest](https://developer.squareup.com/reference/square_2023-12-13/orders-api/search-orders).
type SearchOrdersResponse struct {
	// A list of [OrderEntries](https://developer.squareup.com/reference/square_2023-12-13/objects/OrderEntry) that fit the query conditions. The list is populated only if `return_entries` is set to `true` in the request.
	OrderEntries []OrderEntry `json:"order_entries,omitempty"`
	// A list of [Order](https://developer.squareup.com/reference/square_2023-12-13/objects/Order) objects that match the query conditions. The list is populated only if `return_entries` is set to `false` in the request.
	Orders []Order `json:"orders,omitempty"`
	// The pagination cursor to be used in a subsequent request. If unset, this is the final response. For more information, see [Pagination](https://developer.squareup.com/docs/build-basics/common-api-patterns/pagination).
	Cursor string `json:"cursor,omitempty"`
	// [Errors](https://developer.squareup.com/reference/square_2023-12-13/objects/Error) encountered during the search.
	Errors []ModelError `json:"errors,omitempty"`
}
