/*
 * Square Connect API
 *
 * Client library for accessing the Square Connect APIs
 *
 * API version: 2.0
 * Contact: developers@squareup.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package models

// Details about a refund's destination.
type DestinationDetails struct {
	// Details about a card refund. Only populated if the destination_type is `CARD`.
	CardDetails *DestinationDetailsCardRefundDetails `json:"card_details,omitempty"`
}
