/*
 * Square Connect API
 *
 * Client library for accessing the Square Connect APIs
 *
 * API version: 2.0
 * Contact: developers@squareup.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package models

// Represents a generic time range. The start and end values are represented in RFC 3339 format. Time ranges are customized to be inclusive or exclusive based on the needs of a particular endpoint. Refer to the relevant endpoint-specific documentation to determine how time ranges are handled.
type TimeRange struct {
	// A datetime value in RFC 3339 format indicating when the time range starts.
	StartAt string `json:"start_at,omitempty"`
	// A datetime value in RFC 3339 format indicating when the time range ends.
	EndAt string `json:"end_at,omitempty"`
}
