/*
 * Square Connect API
 *
 * Client library for accessing the Square Connect APIs
 *
 * API version: 2.0
 * Contact: developers@squareup.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package models
// CardCoBrand : Indicates the brand for a co-branded card.
type CardCoBrand string

// List of CardCoBrand
const (
	UNKNOWN_CardCoBrand CardCoBrand = "UNKNOWN"
	AFTERPAY_CardCoBrand CardCoBrand = "AFTERPAY"
	CLEARPAY_CardCoBrand CardCoBrand = "CLEARPAY"
)
