/*
 * Square Connect API
 *
 * Client library for accessing the Square Connect APIs
 *
 * API version: 2.0
 * Contact: developers@squareup.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package models
// SortOrder : The order (e.g., chronological or alphabetical) in which results from a request are returned.
type SortOrder string

// List of SortOrder
const (
	DESC_SortOrder SortOrder = "DESC"
	ASC_SortOrder SortOrder = "ASC"
)
