/*
 * Square Connect API
 *
 * Client library for accessing the Square Connect APIs
 *
 * API version: 2.0
 * Contact: developers@squareup.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package models
// OrderServiceChargeType : 
type OrderServiceChargeType string

// List of OrderServiceChargeType
const (
	AUTO_GRATUITY_OrderServiceChargeType OrderServiceChargeType = "AUTO_GRATUITY"
	CUSTOM_OrderServiceChargeType OrderServiceChargeType = "CUSTOM"
)
