/*
 * Square Connect API
 *
 * Client library for accessing the Square Connect APIs
 *
 * API version: 2.0
 * Contact: developers@squareup.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package models

// Represents filtering and sorting criteria for a [SearchCustomers](https://developer.squareup.com/reference/square_2023-12-13/customers-api/search-customers) request.
type CustomerQuery struct {
	// The filtering criteria for the search query. A query can contain multiple filters in any combination. Multiple filters are combined as `AND` statements.  __Note:__ Combining multiple filters as `OR` statements is not supported. Instead, send multiple single-filter searches and join the result sets.
	Filter *CustomerFilter `json:"filter,omitempty"`
	// Sorting criteria for query results. The default behavior is to sort  customers alphabetically by `given_name` and `family_name`.
	Sort *CustomerSort `json:"sort,omitempty"`
}
